services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile.fuseki
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data:/fuseki/databases
      - ./rdf_triple:/fuseki/data:ro
      - ./fuseki-config.ttl:/opt/fuseki/fuseki-config.ttl:ro
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 15s
      timeout: 5s
      retries: 5

  solr:
    image: solr:9.8.1
    ports:
      - "8983:8983"
    volumes:
      - solr-data:/var/solr
    command: bash -c "solr-precreate food_collection & solr-precreate disease_collection"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/cores?action=STATUS"]
      interval: 15s
      timeout: 5s
      retries: 5

  flask:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data/Foods:/app/assets/images
      - ./data/Diseases:/app/assets/documents
    depends_on:
      fuseki:
        condition: service_healthy
      solr:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
      - SPARQL_URL=http://fuseki:3030/food_disease_kg/sparql
      - FOOD_SOLR_URL=http://solr:8983/solr/food_collection/update?commit=true
      - DISEASE_SOLR_URL=http://solr:8983/solr/disease_collection/update?commit=true
      - FOOD_SOLR_SELECT=http://solr:8983/solr/food_collection/select
      - DISEASE_SOLR_SELECT=http://solr:8983/solr/disease_collection/select
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:5000/api/health', timeout=5).raise_for_status()\" || exit 1"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      flask:
        condition: service_healthy
    environment:
      # Add environment variable for API endpoint if needed
      - API_BASE_URL=http://localhost:5000/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/index.html"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  fuseki-data:
  solr-data: